const DEFAULT_TIME_LIMIT = 2000

const DEFAULT_FRAME_INTERVAL = 1000 / 220

const TOTAL_FRAME_DURATION = Math.round(
  DEFAULT_TIME_LIMIT / DEFAULT_FRAME_INTERVAL,
)

export { DEFAULT_TIME_LIMIT, DEFAULT_FRAME_INTERVAL, TOTAL_FRAME_DURATION }
